### ISSUE TITLE
Das Erste (ARD) Tagesschau missing?

### ISSUE THREAD

**Issue by TPolzer** [mathewmeconry/TV7_EPG_Data#11]
German "Das Erste" (channel "daserste") has a daily program that seems to be strangely missing from the EPG? E.g. Monday, 20. February
- 19:50 - 19:55 "Wetter vor acht" is in the EPG
-  20:00 - 20:15 "Tagesschau" is missing
- 20:15 - 23:15 "Karneval in Köln" is in the EPG.

teleboy.ch web interface looks good, but does seem to be partially confusing it with Tagesschau on SRF1 https://www.teleboy.ch/en/tv-guide/ardhd/25336303/tagesschau

**Comment by mathewmeconry** [comment]
Sometimes I can reproduce it and sometimes not. I guess I hit some limit with the teleboy shadow API. I reduced the intervals that I parse down to only 20mins. Maybe this help

**Comment by mathewmeconry** [comment]
Tagesschau is back in the data. I am not sure if it was the timeframe or a bug from teleboy. Anyhow it is there again. Feel free to reopen the issue if it is missing in the future
