### ISSUE TITLE
Telly is failing to parse recent EPG xml files

### ISSUE THREAD

**Issue by mr-shaba** [mathewmeconry/TV7_EPG_Data#15]
I don't know when this has started to happen, but it appears that Telly isn't able to parse the EPG xml file anymore.

tv7_init7_epg.xml.gz:
"Could not decode xmltv programme" error="XML syntax error on line 1: expected attribute name in element"

tv7_epg.xml.gz:
"Could not decode xmltv programme" error="XML syntax error on line 5591: expected attribute name in element"

**Comment by mathewmeconry** [comment]
Looks like my big update from yesterday doesn't work...
Can you check if you can load this file? It is only a small subset of all the EPG data but should verify if my fixes work
[tv7_init7_epg.xml.gz](https://github.com/user-attachments/files/15591641/tv7_init7_epg.xml.gz)

**Comment by mr-shaba** [comment]
Yes that file seems to work, at least it didn't throw any error in Telly and also Plex didn't complain about it.

From what I see in Plex it contains data for SRF 1, SRF 2 and SRF Info

**Comment by mathewmeconry** [comment]
Great new files have been uploaded that should work now

**Comment by mr-shaba** [comment]
I'm really sorry, unfortunately have to report that the issue appears to be back again, Can't use the EPG files from last night, again parsing error in Telly, and no data shown if loaded directly in an IPTV client.

**Comment by mathewmeconry** [comment]
Hi @mr-shaba 
Sorry for that... It seems that Init7 has some faulty icons in their sources. The issue is tracked now with #39 in the parser repo and should be resolved soon.
