### ISSUE TITLE
Some channels are missing EPG information

### ISSUE THREAD

**Issue by damnms** [mathewmeconry/TV7_EPG_Data#2]
Hi, first of all: thanks for your work, thats a nice thing!

Some of the channels are missing EPG information. 
Is there any way to somehow get them too?
I guess its about 10 or so..? e.g. VIVA

**Comment by mathewmeconry** [comment]
Hi @damnms 

Sure. Just send me a list and I'll try to add them.

**Comment by damnms** [comment]
Hi @mathewmeconry 
This is the complete, current, list. Hope it helps. If you need just those which are currently not listed, i can try to get that too.
Thanks!

```
2M Maroc
3+ HD
3Sat HD
4E
4+ HD
5+ HD
5STAR
5 USA
6ter
Abu Dhabi TV
Alf
Al Jazeera English HD
Al Masriyah
Alsace 20
Al Sharqiya
Anixe HD
ANTENNATRE HD
ARD Alpha
Arirang World
Arte F HD
Arte HD
Atlas TV
BBB Teststream
BBC Four HD
BBC NEWS HD
BBC One HD
BBC Two HD
BBC World News Europe HD
BFM TV
Bibel TV HD
Bloomberg
BN
Boing
Booster TV
BR HD
BVN TV
C1R Europe
C8 HD CH
Canal 24 Horas
Canal Alpha HD
Canal Alpha JU HD
Canale5 HD
CBBC HD
CBeebies HD
CCTV4
Channel 4 HD
Channel 55
CHTV HD
CITV
CNBC Europe
CNN International
Das Erste HD
Die Neue Zeit TV
Disney Channel
DMAX HD
Dubai Sports 3
Dubai TV
Duna TV
DW Europe
E4
EuroNews
Euronews F
Eurosport
Fashion TV
FB TV
Film 4
France 24
France 24 E
France 2 HD
France 3
France 4
France 5
GoTV
Gulli
HABERTURK
hr-fernsehen HD
HSE24 
HSE24 TREND
IRIS
Italia 1 HD
ITV 1 HD
ITV 2
ITV 3
ITV 4
Jordan TV
Kabel1 (Schweiz)
KANAL 7 AVRUPA
Kika HD
Kuwait TV
LA 7
LA7d
la télé HD
LBC Europe
LFM TV
M6 HD
MBC Europe
MDR Sachsen HD
More 4
MTV Schweiz HD
MySports HD D
MySports HD F
NDR HD
Nickelodeon CH HD
NRJ12
NT1
n-tv
Numéro 23
Oman TV
one HD
One TV
ORF1 HD
ORF2 HD
PCNE Chinese
Phoenix HD
ProSieben Maxx
ProSieben (Schweiz)
Puls 8 HD
Qatar TV
Rai 4
Rai Due
Rai HD
Rai Movie
Rai News 
Rai Premium
Rai Sport+ HD
Rai Storia
Rai Tre
Rai Uno
Rai Yoyo
rbb Berlin HD
Real Time
Rete4 HD
Rouge TV HD
RSI LA 1 HD
RSI LA 2 HD
RTK 1
RTL 2 (Schweiz)
RTL 9 HD
RTL CH
RTL Nitro
RTP 1
RTRS plus
RTS 1 HD
RTS 2 HD
RTV Montenegro
Russia Today
S1 HD
Sama Dubai
Sat1 Gold
Sat.1 (Schweiz)
Saudi 1
Schweiz 5
Servus TV HD
Sharjah TV
SIXX
Sky News
SPORT1 HD CH
Sportitalia
Sportitalia 2
Sportitalia 24
SRF1 HD
SRF Info HD
SRFzwei HD
Star TV HD
STERK TV
Super RTL (Schweiz)
Svet Plus
SWISS1 HD
SWR BW HD
tagesschau24 HD
Tele1 HD
Tele 5
TeleBärn HD
TeleBasel HD
Tele Bielingue HD
Teleclub Zoom
TeleD HD
TELELOMBARDIA HD
Tele M1 HD
Tele Ticino HD
TELE TOP HD
Télé Versoix
Tele Z HD
Tele Züri HD
TF1 HD
Thai Global Network
TLC
TMC
Top Calcio 24
Travel
TRT 3-SPOR
TRT TURK
TTN
TV24 HD
TV25 HD
TV5MONDE EUROPE
TV CG
TVE Internacional
TVM3
TVO HD
TVP Polonia
TVR International
TVSH
TV Shqiptar
TV Südostschweiz HD
VH1
VIVA CH HD
VOX (Schweiz)
W9 HD
WDR HD Köln
Welt der Wunder
Welt HD
wetter.tv
ZDF HD
ZDF Info HD
ZDF Neo HD
```

**Comment by mathewmeconry** [comment]
Hi @damnms 

Thanks for the list. 
I just need the channel names which you would like to have additionally.

**Comment by damnms** [comment]
Hi mathew, the list contains:

Tele Top HD
TVO HD
Tele M1 HD
Tele Z HD
TV Südostschweiz HD
Tele Bielingue HD
CHTV HD
Schweiz 5
TeleD HD
Alf
wetter.tv
Teleclub Zoom
MySports HD
Sat1 Gold
VIVA CH HD
Eurosport
TLC
Anixe HD
Welt der Wunder
DW Europe
SWR BW HD
BR HD
WDR HD Köln
MDR Sachsen HD
hr-fernsehen HD

It would be nice to have them all from the list, but those are - at least for me - the important ones.

**Comment by mathewmeconry** [comment]
Thanks for the list. I found few that were missing and some that I can't fetch a this moment. 
To clarify my table below I added this little "information" section which explains which file includes what.

The file [tv7_epg.xml.gz](https://github.com/mathewmeconry/TV7_EPG_Data/blob/master/tv7_epg.xml.gz) includes both sources.
The file [tv7_tele_epg.xml.gz](https://github.com/mathewmeconry/TV7_EPG_Data/blob/master/tv7_tele_epg.xml.gz) the epg information from [https://www.tele.ch/tv-programm](https://www.tele.ch/tv-programm).
The file [tv7_teleboy_epg.xml.gz](https://github.com/mathewmeconry/TV7_EPG_Data/blob/master/tv7_teleboy_epg.xml.gz) includes the epg information from [https://www.teleboy.ch/programm](https://www.teleboy.ch/programm)

| channel | tele | teleboy | all | comment |
| --- | --- | --- | --- | --- |
| Tele Top HD | no | yes | yes | |
| TVO HD | yes | yes | yes | |
| Tele M1 HD | yes | yes | yes | |
| Tele Z HD | no | no | no | Not available in both sources |
| TV Südostschweiz HD | no | yes | yes | |
| Tele Bielingue HD | no | yes | yes | |
| CHTV HD | no | no | no | Not available in both sources |
| Schweiz 5 | no | no | no | Not available in both sources |
| TeleD HD | no | no | no | Not available in both sources |
| Alf | no | no | no | Not available in both sources |
| wetter.tv | no | yes | yes | |
| Teleclub Zoom | no | yes | yes | |
| MySports HD | no | no | no | Not available in both sources |
| Sat1 Gold | no | yes | yes | |
| VIVA CH HD | no | no | no | Not available in both sources |
| Eurosport | yes | yes | yes | tele source included in next update |
| TLC | no | yes | yes | included in next update |
| Anixe HD | yes | yes | yes | tele source included in next update |
| Welt der Wunder | no | no | no | Not available in both sources |
| DW Europe | no | no | no | Not available in both sources |
| SWR BW HD | no | yes | yes | |
| BR HD | no | yes | yes | |
| WDR HD Köln | no | yes | yes | |
| MDR Sachsen HD | no | no | no | Not available in both sources |
| hr-fernsehen HD | yes | no | yes | Not available in both sources |

The commit with the new mappings is linked to this issue

**Comment by damnms** [comment]
Thanks - is there any way to get EPG for VIVA? This is one i really miss and would love to see :) 

I am not sure but i could imagine that those EPG information are available e.g. at this adress:
http://www.webgrabplus.com/epg-channels#s8E

Unfortunately, i have no knowledge in python :(

**Comment by mathewmeconry** [comment]
Currently I don't have time to integrate a new data source.

But it would be helpful if you could validate if the mentioned source has some more missing channels. Then it would be the work worth

**Comment by damnms** [comment]
I fully understand this. If i could write python, i would help you.
It seems like, the epg (horizon.tv) covers nearly all of the channels.
at least, all i checked where supported - so i guess the work will absolutely be worth it
