### ISSUE TITLE
update of channels

### ISSUE THREAD

**Issue by damnms** [mathewmeconry/TV7_EPG_Data#3]
is there any way to help you to get this a bit more stable?
i really appreciate your work, but i sometimes have no epg at all because the channels are not updated.

**Comment by mathewmeconry** [comment]
sorry to that the service is that unstable. I currently had no time to upload the script to a server and run it as a cron.
I'll try to get it running this week
keep you posted

**Comment by damnms** [comment]
no problem, i really appreciate that!
If you need something to let your script run, maybe i can help - i have a VPS where i host my email server.

**Comment by damnms** [comment]
the .xml in the .gz of tv7_epg.xml.gz seems to be broken

**Comment by damnms** [comment]
oh no, seems to be a problem with init7 and their tv backend ... or something is messed up in my lan.

when i go to https://www.init7.net/de/support/faq/TV-andere-Geraete/ and download both the files, and open them, i get an error saying "["Failed to fetch the tv channels!"]"

**Comment by mathewmeconry** [comment]
haven't seen that one...

I get in touch with init7 to get the channels back working

**Comment by mathewmeconry** [comment]
The data is now updated based on the files I got directly from init7 support
Keep you posted if the api is back

**Comment by fuse314** [comment]
The tvchannels api of init7 seems to be working again.

**Comment by mathewmeconry** [comment]
yep it does
