### ISSUE TITLE
INIT7 EPG invalid XML?

### ISSUE THREAD

**Issue by noviceiii** [mathewmeconry/TV7_EPG_Data#5]
Dear all

I am using the INIT7 EPG file for quite a while. Thank you!

For a few days (maybe 2, 3 weeks) I cannot load the EPG information into TELLY any longer. It says the format is invalid...

I did not investigate any further (so not sure if its an issue), thought I come to ask first :-)
Anybody else facing the issue?

Kind regards
N3

```
time="2020-02-24T10:14:44Z" level=error msg="Could not decode xmltv programme" error="the type Date field of date is not a time, value is: 2"
time="2020-02-24T10:14:44Z" level=error msg="error when parsing EPG" error="the type Date field of date is not a time, value is: 2"
time="2020-02-24T10:14:44Z" level=error msg="error when preparing provider" error="the type Date field of date is not a time, value is: 2"
time="2020-02-24T10:14:44Z" level=error msg="error when processing provider" error="the type Date field of date is not a time, value is: 2"
```

**Comment by noviceiii** [comment]
just to add. It is working with xTeVe.

**Comment by mathewmeconry** [comment]
hey @noviceiii 
Sorry just saw the issue now.
Is this still the case?

**Comment by noviceiii** [comment]
Hi @mathewmeconry 
No worries. Thanks for coming back.

The issue may still exist. However I have meanwhile switched from Telly to xTeVe so I cannot retest nor digg further into it.

Kind regards
N3
