### ISSUE TITLE
Keeping the past?

### ISSUE THREAD

**Issue by nicam** [mathewmeconry/TV7_EPG_Data#9]
Hi there!

Thank you a lot for this repository!

I figured out a way to change the tv7 m3u to work with replay TV on Kodi. To make it work properly though, I'd need the EPG also to contain the past week.

Any chance you could also offer an EGP File that also contains the past 7 days?

Thanks for your help!

Pascal

**Comment by nicam** [comment]
In case you want to give it a try, here's the repository :)

https://github.com/nicam/TV7-Kodi-Replay

**Comment by mathewmeconry** [comment]
Hey @nicam 
good use case. let me check if telebody also let me crawl the past.

**Comment by nicam** [comment]
Hey @mathewmeconry 
By now I figured out a way to build my own XML TV file based on Init7's EPG API so I don't think it's necessary anymore :)

**Comment by mathewmeconry** [comment]
ohh they have their own api now?
can you send me the info for this api? then I can maybe change the parser or archive this project and point everybody to it

**Comment by nicam** [comment]
I don't have much info about it, I found it in the source code of another repository here on github that is also generating EPG data. Here's the URL https://github.com/nicam/TV7-Kodi-Replay/blob/main/epg-generator.js#L22

It's only accessible from Init7 Customer IP adresses so you won't be able to run it on circle ci as you have been :)

**Comment by thilojaeggi** [comment]
Hey there.

That link doesn't seem to work anymore (repo gone).

**Comment by nicam** [comment]
@thilojaeggi yes, I removed the repository since now the replay functionality has become a paid feature with Init7

**Comment by jokay** [comment]
At least teleboy.ch did not (yet) increased their prices due to this change.

**Comment by thilojaeggi** [comment]
But if I'm paying for replay it would still work I assume which is why I
don't understand the deletion.

**Comment by nicam** [comment]
@thilojaeggi It seems to work wether you pay or not. I didn't want to run into any legal trouble so I set it to private :)

**Comment by thilojaeggi** [comment]
Ans there's no possibility one might get that repo? ;)

**Comment by nicam** [comment]
@thilojaeggi I'll ask them about the situation with their API.

You're interested in EPG or Replay?

**Comment by thilojaeggi** [comment]
Replay now that you've mentioned it

**Comment by mathewmeconry** [comment]
@nicam sorry that it took over half a year...
but now the parser grabs also the last 7 days from teleboy.
I'll close the Issue once I validated that it work properly

**Comment by mathewmeconry** [comment]
looks like it works

**Comment by thilojaeggi** [comment]
@nicam I'm now paying for TV7 with Replay?
Could you please send me the Git Repo or republish it?

**Comment by nicam** [comment]
@thilojaeggi I talked to Init7, they'll introduce authentication into the API. As soon as this is done I can republish my repository.
